### ISSUE TITLE
"found failing" for test that cannot fail.

### ISSUE THREAD

**Issue by tmr232** [Zac-HD/hypofuzz#22]
I am getting the impression that I am using this wrong...

I have the following test:

```python
from hypothesis import given
from hypothesis.strategies import text

@given(text())
def test_fuzz(s):
    return
```

I run it using:

```shell
hypothesis.exe fuzz -- .\tests\test_fuzz.py
```

It immediately reports that it found a failing input.
When I check the dashboard, I get an exception thrown from inside the Hypothesis code:

![image](https://github.com/Zac-HD/hypofuzz/assets/1386239/88cde5d7-724f-4cc6-91e1-d109fc8c737f)

Am I doing something wrong, or is this a library issue?

**Comment by Zac-HD** [comment]
Library compatibility bug, fixed in the latest version of HypoFuzz - https://github.com/Zac-HD/hypofuzz/issues/21#issuecomment-1546785874

I'm sorry for the confusion this likely caused 😞

**Comment by Zac-HD** [comment]
Library compatibility bug, fixed in the latest version of HypoFuzz - https://github.com/Zac-HD/hypofuzz/issues/21#issuecomment-1546785874

I'm sorry for the confusion this likely caused 😞

**Comment by tmr232** [comment]
I am currently using `23.5.1`:

```
 poetry show hypofuzz
 name         : hypofuzz
 version      : 23.5.1
 description  : Adaptive fuzzing for property-based tests
```

So I think it's a different issue.

**Comment by tmr232** [comment]
Thanks!
