### ISSUE TITLE
docs search on https://hypofuzz.com/docs/ does not work

### ISSUE THREAD

**Issue by pspacek** [Zac-HD/hypofuzz#37]
Browser: Firefox 125.0.1 (64-bit) with clean profile

Example of a broken URL: https://hypofuzz.com/docs/search.html?q=stateful&check_keywords=yes&area=default

(I just typed in `stateful` into the search box and hit Enter key.)

Firefox console logs this:
```
Uncaught ReferenceError: jQuery is not defined
    <anonymous> https://hypofuzz.com/docs/search.html?q=stateful&check_keywords=yes&area=default:113
[search.html:113:7](https://hypofuzz.com/docs/search.html?q=stateful&check_keywords=yes&area=default)
    <anonymous> https://hypofuzz.com/docs/search.html?q=stateful&check_keywords=yes&area=default:113
```
```
Uncaught ReferenceError: jQuery is not defined
    <anonymous> https://hypofuzz.com/docs/search.html?q=stateful&check_keywords=yes&area=default:129
[search.html:129:5](https://hypofuzz.com/docs/search.html?q=stateful&check_keywords=yes&area=default)
    <anonymous> https://hypofuzz.com/docs/search.html?q=stateful&check_keywords=yes&area=default:129
```

I vaguely remember seeing this on other RTD sites as well as a temporary glitch - I think we solved it by updating deps and rebuilding? But I'm not sure and can't locate relevant records, sorry!

**Comment by tybug** [comment]
seems resolve for me now on firefox and chrome - probably because we updated dependencies and rebuilt docs in `24.11.1`! 😄
